server:
  port: 80
spring:
  application:
    name: crowd-zuul
  profiles:
    include: springmvc,springcore,database,redis,eurekaclient

zuul:
  ignored-services: "*"
  sensitive-headers: "*" #在 Zuul 向其他微服務重定向時保持原本頭資訊（請求頭、響應頭）
  routes:
    crowd-portal:
      service-id: crowd-auth
      path: /** #這裡一定要使用兩個「*」號，不然「/」路徑後面的多層路徑將無法訪問