server:
  port: 5000
spring:
  application:
    name: crowd-project
  profiles:
    include: springmvc,springcore,database,redis,eurekaclient

aliyun:
  oss:
    access-key-id: LTAI5tKxyGRnWVdPe8p8szFD
    access-key-secret: bp3N2RSSomNvjwomzsWW7fLlUTouJ3
    bucket-domain: http://inc-lilin-crowd.oss-cn-beijing.aliyuncs.com/
    bucket-name: inc-lilin-crowd
    end-point: http://oss-cn-beijing.aliyuncs.com