server:
  port: 5000
spring:
  application:
    name: crowd-project
  profiles:
    include: springmvc,springcore,database,redis,eurekaclient

aliyun:
  oss:
    access-key-id: LTAI4FtyK7WcqxaiE9ttukNi
    access-key-secret: 43OFOgMghjsitNsNlTGqcpPGgyzqgU
    bucket-domain: http://190830.oss-cn-shenzhen.aliyuncs.com
    bucket-name: 190830
    end-point: http://oss-cn-shenzhen.aliyuncs.com