spring:
  datasource:
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/crowd_admin   #資料庫其他設定，已移到comoon
  thymeleaf:
    cache: false