server:
  port: 4000
spring:
  application:
    name: crowd-auth
  profiles:
    include: springmvc,springcore,database,redis,eurekaclient

short:
  message:
    app-code: 61f2eaa3c43e42ad82c26fbbe1061311
    host: https://feginesms.market.alicloudapi.com
    method: GET
    path: /codeNotice
    sign: 151003
    skin: 84683